name: 'replace md images'
description: 'replace images in markdown to tencent cloud cos url'
inputs:
  token:
    description: 'github token'
    default: ${{ github.token }}
    required: true
  secretId:
    description: 'cos secret id'
    required: true
  secretKey:
    description: 'cos secret key'
    required: true
  bucket:
    description: 'cos bucket'
    required: true
  region:
    description: 'cos region'
    required: true
  prefix:
    description: 'cos prefix'
    required: true
  mdfile:
    description: 'markdown file name'
    required: false
  webhookUrl:
    description: 'work wechat robot webhook url'
outputs:
  result:
    description: 'handled result'
runs:
  using: 'node16'
  main: 'dist/index.js'